CREATE TABLE TESO.TRAA011_PLANCUO_CLAN_AMORT
(
  FH_EFECTIVA       DATE,
  CD_EXPEDIENTE     VARCHAR2(10 CHAR),
  CD_CTE_ALTAMIRA   VARCHAR2(10 CHAR),
  CD_IUC            VARCHAR2(18 CHAR),
  FH_LIQUIDACION    DATE,
  IM_MOVLIQ         NUMBER(17,2),
  NB_TIPMOVI        VARCHAR2(30 CHAR),
  CD_DIVIS          VARCHAR2(3 CHAR),
  NU_PERIOD_REN_INT VARCHAR2(10 CHAR),
  CD_REN_PERIOD_INT VARCHAR2(10 CHAR),
  NU_PERIOD_AMORT	VARCHAR2(10 CHAR),
  CD_PERIOD_AMORT	VARCHAR2(10 CHAR)
)
TABLESPACE TS_DAT400;