CREATE TABLE TESO.TRAA012_IM_GARANTIAS
(
	 CD_CONTRATO		VARCHAR2(12 CHAR)
	,CD_COUNTERPARTY	VARCHAR2(11 CHAR)
	,FH_TRADE			DATE
	,FH_END				DATE
	,NB_PORTAFOLIO		VARCHAR2(25 CHAR)
	,NU_IMP_NOM			NUMBER(17,4)
	,NB_ISIN			VARCHAR2(12 CHAR)
	,NU_DIRT_PRICE		NUMBER(13,7)
	,NU_VALUE			NUMBER(17,4)
	,NU_HAIR_VALUE		NUMBER(17,4)
	,NU_HAIRCUT			NUMBER(13,7)
	,NB_HAIR_RULE		VARCHAR2(10 CHAR)
	,NB_TIP_COL			VARCHAR2(2 CHAR)
	,NB_SEGREGATED		VARCHAR2(1 CHAR)
	,NB_CUSTODIAN		VARCHAR2(20 CHAR)
	,NB_REHYPO			VARCHAR2(1 CHAR)
	,NB_OWERSHIP		VARCHAR2(1 CHAR)
	,NB_DIRECTION		VARCHAR2(8 CHAR)
	,NB_ACOUNT_NUMBER	VARCHAR2(40 CHAR)
	,CD_DIVISA			VARCHAR2(3 CHAR)
)
TABLESPACE TS_DAT400;