CREATE TABLE
 xxx.SENTRY_INTEGRA (
	 FH_M_PROCESO		DATE
	,FH_OPERACION		DATE
	,NB_M_CD_CORP_CTE	CHAR(100)
	,NB_M_CD_GAR_ACT	CHAR(50)
	,NB_M_TP_ACUERDO	CHAR(5)
	,NB_M_IM_GAR_ACT	NUMBER
	,NB_M_IND_TP_GAR	CHAR(7)
	,NB_M_TP_INST_EMI	CHAR(20)
	,NB_M_DV_IMPORT		CHAR(3)
	,NB_M_CD_DIV_GAR	CHAR(3)
	,FH_M_INI_VIG		DATE
	,FH_M_FIN_VIG		DATE
	,NB_M_PAIS_REAL		CHAR(15)
	,NB_M_ORIG_GARAN	CHAR(2)
	,NB_M_ISIN			CHAR(16)
	TABLESPACE xxx		
);

COMMENT ON TABLE xxx.SENTRY_INTEGRA IS 'Tabla SENTRY_INTEGRA';